project_id = "ykvarespqlocurjobxjp"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.market-data]
verify_jwt = false

[functions.financial-news]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
