// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykvarespqlocurjobxjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdmFyZXNwcWxvY3Vyam9ieGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY4ODcsImV4cCI6MjA2NTQ5Mjg4N30.TAxUq-2D6lYgq3f5E2OF2Nq-pI0qoF-GVc82RzEqUqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);